// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'DtrTable.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

DtrTable _$DtrTableFromJson(Map<String, dynamic> json) => DtrTable(
      json['id'] as int?,
      json['plan'] as String?,
      json['state'] as String?,
      json['state_code'] as int?,
      json['discom'] as String?,
      json['discom_code'] as String?,
      json['district'] as String?,
      json['district_code'] as int?,
      json['dtr_village_name'] as String?,
      json['dtr_village_code'] as int?,
      json['dtr_5kva'] as int?,
      json['dtr_6kva'] as int?,
      json['dtr_10kva'] as int?,
      json['dtr_16kva'] as int?,
      json['dtr_25kva'] as int?,
      json['dtr_40kva'] as int?,
      json['dtr_63kva'] as int?,
      json['dtr_100kva'] as int?,
      json['dtr_200kva'] as int?,
      json['dtr_250kva'] as int?,
      json['dtr_300kva'] as int?,
      json['dtr_500kva'] as int?,
      (json['length11kv_ckm'] as num?)?.toDouble(),
      (json['longitude'] as num?)?.toDouble(),
      (json['lattitude'] as num?)?.toDouble(),
      json['dtr_count'] as int?,
      json['total_capacity_kva'] as int?,
      json['created_by'] as String?,
      json['image_path'] as String?,
      json['asset_number'] as String?,
      json['from_asset_number'] as String?,
      json['feeder_name'] as String?,
      json['dtr_400kva'] as int?,
    );

Map<String, dynamic> _$DtrTableToJson(DtrTable instance) => <String, dynamic>{
      'id': instance.id,
      'plan': instance.plan,
      'state': instance.state,
      'state_code': instance.stateCode,
      'discom': instance.discom,
      'discom_code': instance.discomCode,
      'district': instance.district,
      'district_code': instance.districtCode,
      'dtr_village_name': instance.dtrVillageName,
      'dtr_village_code': instance.dtrVillageCode,
      'dtr_5kva': instance.dtr5kva,
      'dtr_6kva': instance.dtr6kva,
      'dtr_10kva': instance.dtr10kva,
      'dtr_16kva': instance.dtr16kva,
      'dtr_25kva': instance.dtr25kva,
      'dtr_40kva': instance.dtr40kva,
      'dtr_63kva': instance.dtr63kva,
      'dtr_100kva': instance.dtr100kva,
      'dtr_200kva': instance.dtr200kva,
      'dtr_250kva': instance.dtr250kva,
      'dtr_300kva': instance.dtr300kva,
      'dtr_500kva': instance.dtr500kva,
      'length11kv_ckm': instance.length11kvCkm,
      'longitude': instance.longitude,
      'lattitude': instance.lattitude,
      'dtr_count': instance.dtrCount,
      'total_capacity_kva': instance.totalCapacityKva,
      'created_by': instance.createdBy,
      'image_path': instance.imagePath,
      'asset_number': instance.assetNumber,
      'from_asset_number': instance.fromAssetNumber,
      'feeder_name': instance.feederName,
      'dtr_400kva': instance.dtr400kva,
    };
